Repository agoraxyz/gold.xyz, pull requests merged in 2022-02, with the labels that each got.

#36 Auction win animation
  package.json
  public/img/coin.png
  src/components/[auction]/Countdown.tsx
  src/components/_app/Coinfetti.tsx
  src/contract-logic/index.ts
  src/contract-logic/wasm-factory/instructions_bg.js
  src/contract-logic/wasm-factory/instructions_bg.wasm
  src/contract-logic/wasm-factory/instructions_bg.wasm.d.ts
  src/hooks/useWindowSize.ts
  src/pages/[auction]/[[...cycleNumber]].tsx
  src/pages/_app.tsx
Labels: enhancement

#29 New auction page design with progress bar
  src/components/[auction]/Bid/Bid.tsx
  src/components/[auction]/Bid/hook/usePlaceBid.ts
  src/components/[auction]/Countdown.tsx
  src/components/[auction]/ProgressBar.tsx
  src/components/common/Layout/Layout.tsx
  src/contract-logic/consts.ts
  src/pages/[auction]/[[...cycleNumber]].tsx
  src/theme/components/stat.ts
Labels: enhancement

#57 Displaying alert & auto refreshing on cycle end
  package-lock.json
  package.json
  src/components/[auction]/CycleEndAlert.tsx
  src/components/[auction]/hooks/useAuction.ts
  src/components/[auction]/hooks/useCycle.ts
  src/pages/[auction]/[[...cycleNumber]].tsx
Labels: enhancement, invalid, prio 1

#65 Pinata integration
  .env
  package-lock.json
  package.json
  src/components/create-auction/NFTData/NFTData.tsx
  src/components/create-auction/SubmitButton.tsx
  src/components/create-auction/hooks/useDropzone.ts
  src/components/create-auction/hooks/useStartAuction.ts
  src/pages/api/pinata-key.ts
  src/pages/create-auction.tsx
  src/utils/pinataUpload.ts
Labels: enhancement

#67 fix: Frozen auction win animation
  src/components/_app/Coinfetti.tsx
Labels: bug
